refactor: rename workflow steps for clarity and streamline DuckDB build process

diff --git a/.github/workflows/build(RISC-V).yml b/.github/workflows/build(RISC-V).yml
--- a/.github/workflows/build(RISC-V).yml
+++ b/.github/workflows/build(RISC-V).yml
@@ -13,7 +13,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Install dependent and start environment
+      - name: Install QEMU and OpenSBI
         run: |
           sudo apt-get install -y qemu-system u-boot-qemu openssh-server screen sshpass opensbi
           wget -O debian.zip https://gitlab.com/api/v4/projects/giomasce%2Fdqib/jobs/artifacts/master/download?job=convert_riscv64-virt
@@ -31,13 +31,13 @@ jobs:
             -kernel /usr/lib/u-boot/qemu-riscv64_smode/uboot.elf \
             -append "root=LABEL=rootfs console=ttyS0" \
             -nographic
-      
-      - name: Wait for qemu to start
-        run: sleep 150
 
-      - name: Build RISC-V Version DuckDB
+      - name: Install DuckDB Dependencies
         run: |
           sshpass -p 'root' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost "apt-get update && apt-get install -y git g++ cmake ninja-build libssl-dev"
           sshpass -p 'root' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost "git clone https://github.com/duckdb/duckdb.git"
-          sshpass -p 'root' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost "cd duckdb && CORE_EXTENSIONS='tpch' GEN=ninja CC='gcc -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b' CXX='g++ -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b'  make"
+
+      - name: Build RISC-V Version DuckDB
+        run: |
+          sshpass -p 'root' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p 2222 root@localhost "cd duckdb && GEN=ninja CC='gcc -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b' CXX='g++ -march=rv64gcv_zicsr_zifencei_zihintpause_zvl256b' make && ./build/release/duckdb -c 'PRAGMA platform;' && make clean && echo 'DOCKER TEST RESULT: SUCCESS' || (echo 'DOCKER TEST RESULT: FAILURE' && make clean)"
       
